range() 和arange()这两种方式区别是？
range() 和arange() 的返回类型不同，range()返回的是range；而np.arange()返回的是ndarray类型；

range()不支持步长为小数，而arange()支持步长(step)为小数

range()和arange()都可用于迭代，而arange作用远不止于此，它是一个序列，可被当做向量使用。

range() 函数是python 自带的函数，而arange() 是numpy 库中的函数

In [10]:
nparr=np.array([i for i in range(10)])
arr=np.arange(0,10)

NameError: name 'np' is not defined

In [ ]:
import numpy as np

In [ ]:
nparr

In [ ]:
np.arange(0,10)

In [ ]:
type(nparr)

In [ ]:
type(arr)

In [ ]:
np.zeros(10)

In [ ]:
np.zeros((2,2),dtype=float)

In [ ]:
np.full((2,2),dtype=float,fill_value=12)

### arange 和 linspace
要是知道步长用arange  不知道步长,知道space，用linspace，linspace包括终止点 arange不包括
If you know the step size, use arange. If you don't know the step size,know space, use linspace. 
Linspace includes the termination point. arange does not include

In [ ]:
no=np.arange(0,2,0.2)

In [ ]:
no

In [ ]:
np.linspace(0,20,11)

### random
    randint包左不包右
    np.random.random(3) 一维
    np.random.random((3,5)) 二维，浮点数在0-1之间
    np.random.random((6,3,5)) 三维，浮点是0-1之间，6个（3，5）的向量

In [ ]:
np.random.randint(0,1,size=10)

In [ ]:
np.random.randint(0,4,size=(3,5))

In [ ]:
np.random.seed(1)

In [ ]:
np.random.randint(0,4,size=(3,5))

In [ ]:
np.random.random((3,5))

In [ ]:
  np.random.random((6,3,5))

In [ ]:
np.random.random(3)

np.random.normal(0,1,(2,3,5)) 均值为0 方差为1 三维的，（3，5）的矩阵

In [ ]:
np.random.normal(0,1,(2,3,5))

In [ ]:
import numpy as np

### Basic Attributes
+ .ndim查维度

+ .shape查shape

+ .size查元素个数（not number nor long）

In [ ]:
x1=np.arange(10)
x1

In [ ]:
x2=np.arange(15).reshape(3,5)
x2

In [ ]:
x1.ndim

In [ ]:
x2.ndim

In [ ]:
x1.shape

In [ ]:
x2.shape

In [ ]:
x1.size

In [ ]:
x2.size

### numpy array data access dim1
+ a[0] index 0
+ a[-1] the last one

In [ ]:
x1[0]

In [ ]:
x1[3]

In [ ]:
x1[-1]

### numpy array data access dim2
+ access one data 
    1. x2[0][0]
    2. x2[(0,0)]/x2[0,0] recommend this one
#### 切片(1dim)
    1. x1[0:5] from 0 to 5 exclude 5,left default zero
    2. x1[:5] from 0 to 5 exclude 5
    3. x1[5:] from 5 to end,include last one
    4. x1[::2]from begin to end by step 2 
    5. x1[::-1]from end to begin by step 1

In [ ]:
x2[0][0]

In [ ]:
x2[(0,0)]

In [ ]:
x2[0,0]

In [ ]:
x1[:5]

In [ ]:
x1[0:5]

In [ ]:
x1[5:]

In [ ]:
x1[::2]

In [ ]:
x1[::-1]

#### split(2dim)
    1. x2[:2,:3] first two rows and first three columns
    2. x2[:2] first two elements
    3. x2[:2][:1] first take the first two elements, then the first one
    4. x2[:2,::2] 前两行，在这两行中，列为从头到尾步幅为2
    5. x2[::-1,::-1]行是从头到尾，倒着数。列是从头到尾，倒着数。(对整个矩阵做反转操作)
    6. x2[0,:]第一行，所有列（变为一维向量，取第一行）
    7. x2[:,0]第一列，所有行（变为一维向量，取第一列）
#### 在使用切片取部分数据时候，是直接在元数据上操作，即使赋值了新变量，也是直接操作的元数据
#### if wanna operate the copy, you need to use the. copy()
    example:  subx2=x2[:2,:3].copy()

In [ ]:
x2[:2,:3]

In [ ]:
 x2[:2]

In [ ]:
x2[:2][:1]

In [ ]:
x2[:2][:3]

In [ ]:
x2[:2,::2]

In [ ]:
x2[::-1,::-1]

In [ ]:
 x2[0,:]

In [ ]:
x2[:,0]

In [ ]:
subx2=x2[:2,:3].copy()
subx2

In [ ]:
subx2[0,0]=100
subx2

In [ ]:
x2

### reshape
+ x.reshape同样不改变数组自身。赋值之后也不会改变，A=x1.reshap(3,5)
#### 不整除的时候报错，所以即使使用自动计算，首先你得确定他是能整除的
#### An error is reported when it is not divisible, so even if you use automatic calculation, you must first make sure that it can be divisible
+ x1.reshape(5,-1)有5行，每行有几个元素，不管，自动计算。


In [ ]:

A=x1.reshape(2,5)
A

In [ ]:
x1

In [ ]:
x1.reshape(5,-1)

### Merge and split
  #### concatenate([z,z,x]) dim不同会报错
  #### 有个axis=0（行）/1（列）的参数。按照行的方向 
  不赋值，无保存，赋值之后才会保存拼接结果
  
  #### vstack的容错性更好，dim不同不报错，但是他不是拼接，他是摞起来luo,hstack横起来 。
  容错是指维度不同可以堆叠，不是任何都可以。
  例如 2*3横向1*3就不可以 纵向堆叠可以

In [ ]:
x=np.array([1,2,3])
y=np.array([4,5,6])
np.concatenate([x,y])

In [ ]:
z=np.array([[1,2,2],[5,6,6]])
np.concatenate([z,z])

In [ ]:
B=np.vstack([x,z])

In [ ]:
B

### split
 split 传入分割对象和分割点，即使分割点为1个，也要用数组传递 example如下
 Pass in the split object and split point. Even if there is one split point, use an array to pass an example as follows
 
 ### the same to 2dim
 2dim 的时候视一个数组为一个元素去分割。Treat an array as an element to split
 axis指定行还是列。0/1  有demo如下
 #### 所有需要指定行0列1的方法都有更直观的函数
 比如，np.split(x,[2],axis=1)可以替换成np.vsplit(a,[2])

In [ ]:
x=np.arange(0,10)
x

In [ ]:
x1,x2,x3=np.split(x,[3,7])
x1,x2,x3

In [ ]:
x1,x2=np.split(x,[3])
x1,x2

In [ ]:
a=np.arange(16).reshape(4,4)
a

In [ ]:
a1,a2=np.split(a,[2],axis=0)
a2

In [ ]:
a1,a2=np.split(a,[2],axis=1)
a1

 ### Practical application of segmentation: distinguish X and y with supervised data
 demo

In [ ]:
X,y=np.hsplit(a,[-1])
X

In [ ]:
a

In [ ]:
 y=y.reshape(-1)
y

In [ ]:
y=y[:,0]
y

### np.array operation

In [12]:
import numpy as np

In [9]:
L=[i for i in range(10)]
L,type(L)

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], list)

In [8]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
L1=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
L1,type(L1)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), numpy.ndarray)

In [25]:
L2=np.arange(10)
L2,type(L2)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), numpy.ndarray)

In [26]:
2*L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

#### surprising 2*L  Python just connects it, not multiplication
输出[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

#### list in python is slower than numpy ,and the latter is support multiplication and more functions

In [44]:
A=[3*e for e in L]
A,type(A)

([0, 3, 6, 9, 12, 15, 18, 21, 24, 27], list)

In [46]:
%%time 
A=np.array(2*e for e in L)
A

Wall time: 0 ns


In [54]:
L=np.arange(10)

In [55]:
A=np.array(2*e for e in L)
A

array(<generator object <genexpr> at 0x0000019090FC9D00>, dtype=object)

In [56]:
2*L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### universal functions
add sub mul div
abs sin exp power log/log2

In [58]:
A=np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [59]:
A+1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [60]:
A-1

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [61]:
2*A

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [62]:
A/2

array([[ 0. ,  0.5,  1. ,  1.5],
       [ 2. ,  2.5,  3. ,  3.5],
       [ 4. ,  4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ,  7.5]])

In [63]:
A%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]], dtype=int32)

In [64]:
A//2

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5],
       [6, 6, 7, 7]], dtype=int32)

In [65]:
A**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])

In [66]:
np.exp(A)

array([[  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
          2.00855369e+01],
       [  5.45981500e+01,   1.48413159e+02,   4.03428793e+02,
          1.09663316e+03],
       [  2.98095799e+03,   8.10308393e+03,   2.20264658e+04,
          5.98741417e+04],
       [  1.62754791e+05,   4.42413392e+05,   1.20260428e+06,
          3.26901737e+06]])

In [69]:
np.power(3,A)#3的x次方

array([[       1,        3,        9,       27],
       [      81,      243,      729,     2187],
       [    6561,    19683,    59049,   177147],
       [  531441,  1594323,  4782969, 14348907]], dtype=int32)

### matrix operation
#### A*B Multiplication of corresponding elements ，not matrix multiplication
#### A.dot(B) matrix multiplication

In [71]:
A=np.arange(8).reshape(2,4)
A

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [72]:
A.T

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

### more often use vector and matrices for operatins

In [73]:
B=np.array([1,2,3])
B

array([1, 2, 3])

In [74]:
A+B#ValueError: operands could not be broadcast together with shapes (2,4) (3,) 
#vector num different

ValueError: operands could not be broadcast together with shapes (2,4) (3,) 

In [75]:
A=np.arange(9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [76]:
A+B# that ok.althought dim different.
#treat vector as a num

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

### handle the addition of vector and metrix usually do vstack or tile

In [77]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [78]:
B

array([1, 2, 3])

In [81]:
np.vstack([B]*A.shape[0])+A

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [84]:
# the same to vastack
#mean stack st. row stack 3times,column stack 1times .then do add oper
np.tile(B,(3,1))+A

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])