range() 和arange()这两种方式区别是？
range() 和arange() 的返回类型不同，range()返回的是range；而np.arange()返回的是ndarray类型；

range()不支持步长为小数，而arange()支持步长(step)为小数

range()和arange()都可用于迭代，而arange作用远不止于此，它是一个序列，可被当做向量使用。

range() 函数是python 自带的函数，而arange() 是numpy 库中的函数

In [11]:
nparr=np.array([i for i in range(10)])
arr=np.arange(0,10)

In [2]:
import numpy as np

In [7]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
type(nparr)

numpy.ndarray

In [12]:
type(arr)

numpy.ndarray

In [37]:
range(10)

TypeError: 'range' object is not callable

In [38]:
L=[i for i in range(10)]

TypeError: 'range' object is not callable

In [40]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [42]:
np.zeros((2,2),dtype=float)

array([[ 0.,  0.],
       [ 0.,  0.]])

In [44]:
np.full((2,2),dtype=float,fill_value=12)

array([[ 12.,  12.],
       [ 12.,  12.]])

### arange 和 linspace
要是知道步长用arange  不知道步长,知道space，用linspace，linspace包括终止点 arange不包括

In [50]:
no=np.arange(0,2,0.2)

In [51]:
no

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8])

In [53]:
np.linspace(0,20,11)

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.])

### random
    randint包左不包右
    np.random.random(3) 一维
    np.random.random((3,5)) 二维，浮点数在0-1之间
    np.random.random((6,3,5)) 三维，浮点是0-1之间，6个（3，5）的向量

In [55]:
np.random.randint(0,1,size=10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [58]:
np.random.randint(0,4,size=(3,5))

array([[1, 3, 0, 0, 3],
       [1, 3, 1, 3, 0],
       [0, 1, 0, 3, 1]])

In [59]:
np.random.seed(1)

In [60]:
np.random.randint(0,4,size=(3,5))

array([[1, 3, 0, 0, 3],
       [1, 3, 1, 3, 0],
       [0, 1, 0, 3, 1]])

In [64]:
np.random.random((3,5))

array([[ 0.66974604,  0.93553907,  0.84631092,  0.31327352,  0.52454816],
       [ 0.44345289,  0.22957721,  0.53441391,  0.91396202,  0.45720481],
       [ 0.43069857,  0.93912779,  0.77838924,  0.71597052,  0.8027575 ]])

In [65]:
  np.random.random((6,3,5))

array([[[ 0.09280081,  0.51815255,  0.86502025,  0.82914691,  0.82960336],
        [ 0.27304997,  0.0592432 ,  0.67052804,  0.59306552,  0.6716541 ],
        [ 0.41178788,  0.1975509 ,  0.28962964,  0.14212014,  0.78331447]],

       [[ 0.41253884,  0.03417131,  0.62402999,  0.66063573,  0.29849529],
        [ 0.44613451,  0.22212455,  0.07336417,  0.46923853,  0.09617226],
        [ 0.90337017,  0.11949047,  0.52479938,  0.083623  ,  0.91686133]],

       [[ 0.91044838,  0.29893011,  0.58438912,  0.56591203,  0.61393832],
        [ 0.95653566,  0.26097898,  0.23101542,  0.53344849,  0.94993814],
        [ 0.49305959,  0.54060051,  0.7654851 ,  0.04534573,  0.13996612]],

       [[ 0.79240359,  0.02980136,  0.88312548,  0.54078819,  0.44798018],
        [ 0.89213587,  0.37758434,  0.53842469,  0.65229888,  0.36126102],
        [ 0.57100856,  0.63783648,  0.12631489,  0.69020459,  0.6477494 ]],

       [[ 0.35393909,  0.76323305,  0.35653172,  0.75278835,  0.88134183],
        [ 0.01166

In [66]:
np.random.random(3)

array([ 0.19195608,  0.4643115 ,  0.23036281])

np.random.normal(0,1,(2,3,5)) 均值为0 方差为1 三维的，（3，5）的矩阵

In [67]:
np.random.normal(0,1,(2,3,5))

array([[[-1.46829223,  0.04155277,  0.02683149, -0.641126  , -0.36931625],
        [-1.16729452,  0.02454542, -0.98237626, -0.3029153 , -0.57041883],
        [-0.9307552 , -0.77458086,  0.14652259, -0.85413244, -1.83582581]],

       [[-1.14010497, -0.5924452 ,  0.88200328,  0.77883804,  1.49903239],
        [ 1.54290932, -0.44773169, -1.77769234, -1.79183523, -1.00506543],
        [-0.40037634,  0.53625837,  1.29978471,  0.09418039, -0.28316929]]])

In [69]:
np.random.normal?